
from fastapi import FastAPI, File, UploadFile, Form, HTTPException
from fastapi.responses import JSONResponse
import os
import base64
import uuid
import operator
from typing import List, Dict, Optional, Annotated
from typing_extensions import TypedDict
from PIL import Image
import io
import logging

# LangGraph / Groq imports
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from langchain_core.messages import HumanMessage
from langchain_groq import ChatGroq

# --- Config from environment ---
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    raise RuntimeError("GROQ_API_KEY environment variable is required.")

# Explicitly pin a supported model — llama-4-scout is being deprecated by Groq.
GROQ_MODEL = os.getenv("GROQ_MODEL", "openai/gpt-oss-120b")
GROQ_TEMPERATURE = float(os.getenv("GROQ_TEMPERATURE", "0.7"))

# Optional Google/Gemini config (not required)
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
GEMINI_MODEL = os.getenv("GEMINI_MODEL")  # if you wire up Gemini later

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize Groq client (reads from env for key)
os.environ["GROQ_API_KEY"] = GROQ_API_KEY
groq_llm = ChatGroq(
    model_name=GROQ_MODEL,
    temperature=GROQ_TEMPERATURE,
    reasoning_effort="none",
    model_kwargs={"include_reasoning": False},
)

import re

def strip_thinking(text: str) -> str:
    """Fallback: strip any <think>...</think> block that slips through,
    in case a given model/provider combo ignores include_reasoning."""
    if not text:
        return text
    return re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()

# --- Graph state definition ---
# Using a plain dict as state causes each node's return value to overwrite
# existing keys (including "logs"), so only the last node's logs survive.
# TypedDict + Annotated[list, operator.add] makes "logs" accumulate across
# nodes instead of being clobbered.
class GraphState(TypedDict, total=False):
    image_path: Optional[str]
    image_b64: Optional[str]
    client_name: str
    ad_description: str
    platforms: List[str]
    base_caption: str
    scheduled_date: str
    generated_posts: Dict[str, str]
    schedule_time: str
    logs: Annotated[List[str], operator.add]


# --- Node implementations ---
def analyze_image_node(state: dict):
    """
    Fallback image analysis: uses PIL to extract simple metadata and
    asks the groq model to craft a short image-context caption using ad_description.
    (If you later enable a vision LLM like Gemini, replace this node to call it.)
    """
    logs = []
    image_b64 = state.get("image_b64")
    ad_description = state.get("ad_description", "")
    img_meta_text = ""

    if image_b64:
        try:
            image_bytes = base64.b64decode(image_b64)
            img = Image.open(io.BytesIO(image_bytes))
            img_meta_text = f"image width={img.width}, height={img.height}, mode={img.mode}"
            logs.append(f"PIL metadata extracted: {img_meta_text}")
        except Exception as e:
            logs.append(f"Failed to decode/process image: {e}")

    # Compose a prompt for the groq LLM to produce a short "image context" description
    prompt = (
        "You are a marketing assistant. Given the ad description and any basic image metadata, "
        "write one short sentence that describes the visual elements or the vibe of the ad for use in captions.\n\n"
        f"Ad description: {ad_description}\n"
        f"Image metadata: {img_meta_text}\n"
        "Keep it concise and suitable to embed inside social media captions."
    )

    try:
        resp = groq_llm.invoke(prompt)
        base_caption = strip_thinking(resp.content.strip())
        logs.append("Image context generated by Groq.")
    except Exception as e:
        base_caption = f"{ad_description} ({img_meta_text})"
        logs.append(f"Groq image context failed, falling back to metadata: {e}")

    state["base_caption"] = base_caption
    state.setdefault("logs", []).extend(logs)
    return {"base_caption": base_caption, "logs": logs}


def generate_captions_with_groq(state: dict):
    posts: Dict[str, str] = {}
    platforms = state.get("platforms", [])
    client_name = state.get("client_name", "Client")
    ad_description = state.get("ad_description", "")
    base_caption = state.get("base_caption", "")

    logs = []
    if not platforms:
        logs.append("WARNING: 'platforms' was empty when generate node ran; no posts will be created.")

    for platform in platforms:
        prompt = (
            f"Write a high-converting {platform} social post for {client_name}.\n"
            f"Description: {ad_description}\n"
            f"Image context: {base_caption}\n"
            "Make it match the platform tone, include relevant emojis and hashtags as appropriate, "
            "and keep it short enough for the platform."
        )
        try:
            resp = groq_llm.invoke(prompt)
            posts[platform] = strip_thinking(resp.content.strip())
        except Exception as e:
            posts[platform] = f"{ad_description} {base_caption}"
            logs.append(f"Groq generation failed for {platform}: {e}")

    logs.append(f"Generated captions for {len(platforms)} platforms.")
    state["generated_posts"] = posts
    state.setdefault("logs", []).extend(logs)
    return {"generated_posts": posts, "logs": logs}


def scheduler_node(state: dict):
    scheduled_at = state.get("scheduled_date", "ASAP")
    logs = [f"Posts scheduled for {scheduled_at}"]
    state["schedule_time"] = scheduled_at
    state.setdefault("logs", []).extend(logs)
    return {"schedule_time": scheduled_at, "logs": logs}


# --- Build graph once at startup ---
def build_graph():
    workflow_v2 = StateGraph(GraphState)
    workflow_v2.add_node("analyze", analyze_image_node)
    workflow_v2.add_node("generate", generate_captions_with_groq)
    workflow_v2.add_node("scheduler", scheduler_node)

    workflow_v2.set_entry_point("analyze")
    workflow_v2.add_edge("analyze", "generate")
    workflow_v2.add_edge("generate", "scheduler")
    workflow_v2.add_edge("scheduler", END)

    checkpointer = MemorySaver()
    app_v2 = workflow_v2.compile(checkpointer=checkpointer)
    return app_v2

app_v2 = build_graph()

# --- FastAPI app ---
from fastapi import Depends
from fastapi.middleware.cors import CORSMiddleware

api = FastAPI(title="Marketing Agency Agent")

# Allow browser-based frontends (e.g. an AI Studio app) to call this API.
# Using "*" since this endpoint is currently public/unauthenticated anyway.
# If you add auth later, tighten this to your actual frontend's origin(s).
api.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

@api.get("/")
async def root():
    """Simple root endpoint so GET / doesn't 404 (used by uptime/health checks)."""
    return {"status": "ok", "service": "Marketing Agency Agent"}


@api.get("/health")
async def health():
    """Lightweight health check endpoint."""
    return {"status": "healthy"}


@api.post("/generate")
async def generate(
    client_name: str = Form(...),
    ad_description: str = Form(...),
    platforms: str = Form(...),  # comma-separated list
    scheduled_date: Optional[str] = Form(None),
    image: Optional[UploadFile] = File(None),
):
    """
    Generate platform-specific posts from an uploaded image and campaign info.

    - client_name: name of the client
    - ad_description: short textual description of ad (product, tagline)
    - platforms: comma-separated list, e.g. "Instagram,LinkedIn"
    - scheduled_date: optional schedule string
    - image: optional image file
    """
    # Read image bytes and convert to base64 if provided
    image_b64 = None
    if image:
        try:
            image_bytes = await image.read()
            image_b64 = base64.b64encode(image_bytes).decode("utf-8")
        except Exception as e:
            raise HTTPException(status_code=400, detail=f"Failed to read uploaded image: {e}")

    platform_list = [p.strip() for p in platforms.split(",") if p.strip()]

    if not platform_list:
        raise HTTPException(
            status_code=400,
            detail=(
                "No valid platforms provided. 'platforms' must be a non-empty "
                "comma-separated string, e.g. 'Instagram,LinkedIn'."
            ),
        )

    inputs = {
        "image_path": None,
        "image_b64": image_b64,
        "client_name": client_name,
        "ad_description": ad_description,
        "platforms": platform_list,
        "base_caption": "",
        "logs": [],
        "scheduled_date": scheduled_date or "ASAP",
    }

    # Unique config/thread id for the run
    config = {"configurable": {"thread_id": str(uuid.uuid4())}}

    try:
        # Stream the workflow to completion
        for _out in app_v2.stream(inputs, config):
            # We don't need to do anything per step; streaming advances the workflow.
            pass

        final_state = app_v2.get_state(config).values
        # final_state should be a dict-like structure
        generated_posts = final_state.get("generated_posts", {})
        schedule_time = final_state.get("schedule_time", final_state.get("scheduled_date", "ASAP"))
        logs = final_state.get("logs", [])

        return JSONResponse({
            "client_name": client_name,
            "generated_posts": generated_posts,
            "schedule_time": schedule_time,
            "logs": logs
        })

    except Exception as e:
        logger.exception("Workflow execution failed")
        raise HTTPException(status_code=500, detail=f"Workflow execution failed: {e}")
